### ISSUE TITLE
example code is broken

### ISSUE THREAD

**Issue by anoushk1234** [obi1kenobi/cargo-semver-checks-action#26]
```yaml
- name: Check semver
  uses: obi1kenobi/cargo-semver-checks-action@v2
- name: Publish to crates.io
  run: # your `cargo publish` code here
  ``` 
GitHub action errors when I use `obi1kenobi/cargo-semver-checks-action@v2` also the link on top of the repo re directing to the marketplace is broken giving a 404.
